### ISSUE TITLE
"Goodbye"/"goodbye"

### ISSUE THREAD

**Issue by JacobKnox** [Jeremyb498/Artificial-Intelligence#1]
I programmed Sherlock BETA 01.00.05 to say "That's wonderful!" to "Good" or "good", but then when I tried to program it to say "Goodbye. Have a good day!" to "Goodbye" or "goodbye" it said "That's wonderful!" to "goodbye". How would I fix that?

**Comment by Jeremyb498** [comment]
Put a space in the code after "Good" so it is 
"Good " instead then it will only pick up when hoof has a space after it.

**Comment by Jeremyb498** [comment]
Or a period would work to.

**Comment by Jeremyb498** [comment]
There are specific ways but It is more complex and I would need to do it manually probably
